### ISSUE TITLE
Runs erroneously marked as overdue

### ISSUE THREAD

**Issue by briochh** [jtwhite79/pestpp#1]
I have recently seen a few (possibly panther related) timing issues using pestpp-ies (win64, on develop).

Previously I had a run start at (e.g.) 20:59 and return at 23:02 but report a 183 minute run time - I didn’t think too much of it at the time. 

More recently I have had all runs being sent and overdue run kill signal (seconds to 10 mins) after the first run completes. The .rmr ([RmSouth_cal.rmr.txt](https://github.com/jtwhite79/pestpp/files/2264465/RmSouth_cal.rmr.txt)) details the timing of the issue but in summary:
101 realisations are initialised on 101 salves. 29 realisations fail early (this is expected) and the first realisation completes after 89 mins (also expected, around the anticipated fastest run time). All remaining realisations are, almost immediately, sent the kill signal. pestpp options are as detailed below. One thing that jumps out to be is that the run that completes is started at 21:59:28 so possibly the internal calculation of run time is crazy short (an extreme example of that previous encounter above?!) and therefore all of the running jobs are immediately marked as overdue? - that is about all I have got... 

`++OVERDUE_GIVEUP_FAC(3.0)`
`++OVERDUE_RESCHED_FAC(3.1)`
`++MAX_RUN_FAIL(1)`
`++ies_localizer(localizer.mat)`
`++OVERDUE_GIVEUP_MINUTES(360)`
`++ies_parameter_ensemble(rm_south.par.jcb)`
`++sweep_output_csv_file(rm_south.out.jcb)`
`++sweep_parameter_csv_file(rm_south.par.jcb)`
`++ies_obs_en(obs.csv)`
`++ies_bad_phi(1e+30)`

**Comment by jtwhite79** [comment]
Thanks for the heads up, B.  I've been making a few mods to the run mgr this week in the ``feature_morelocal`` branch - I'm running through the tests now, if no issues, I'll merge it in to ``develop`` ASAP.   If that doesn't fix your problem, I might need to get your files and (try) to debug...

**Comment by briochh** [comment]
Hey @jtwhite79, the .exe in `feature_morelocal` branch seems to have somehow cracked that nut, thanks!
Also, loving the extra run-time feedback: 
`sending kill request. reason: overdue. duration:360.001, avg:205.807` tidy!
