### ISSUE TITLE
Use lowercase identifiers

### ISSUE THREAD

**Issue by mwtoews** [jtwhite79/pestpp#14]
Most identifiers in PEST[_HP] appear to be lower case. That is, if you had sim.pst with mixed-case observation groups/names, observation groups/names, the outputs from `pest sim.pst` in the .rec, .res., .rei,  .par files show only lowercase identifiers. And looking thru PEST code, I see that subroutine `lowcas` is called more often that `upcas`. (And `upcas` is primarily used within `#ifdef CAPFILE` blocks to refer to uppercase filenames to give them that great DOS-look).

So far, PEST++ has a bit of a mix of upper and lower case used internally and visible in output files. For example, the .obs.csv, .par.csv and .group.csv files use upper case, but the .upg.csv file uses lowercase. This can be problematic, e.g. when matching pandas dataframes from a .par.csv file to a pyemu par object, which uses lowercase names (in this instance, the solution is to change the column names of the dataframe to lowercase).

So a suggested plan is to revise where `pest_utils::upper_` is used, and consider turning them into `pest_utils::lower_`. Here they are:
```
$ git grep --count "pest_utils::upper_"
src/libs/common/utilities.cpp:4
src/libs/linear_analysis/covariance.cpp:16
src/libs/linear_analysis/linear_analysis.cpp:13
src/libs/opt/sequential_lp.cpp:4
src/libs/pestpp_common/Ensemble.cpp:5
src/utilities/ascii2pbin/ascii2pbin.cpp:1
```

**Comment by jtwhite79** [comment]
Big facepalm here.  I mistakenly thought pest did upper case.  Thanks for the heads up Mike.  This will be changed asap.
