### ISSUE TITLE
Parameter offset

### ISSUE THREAD

**Issue by None72** [jtwhite79/pestpp#3]
I have a Pest model with a parameter offset and run it with Pestpp-ies.    With the initial run everything appears fine, but for the second run the parameter reduces again by that offset.

**Comment by jtwhite79** [comment]
Thanks for the heads up - there was indeed as issue with applying ``scale`` and/or ``offset`` that only showed up in the model input files (not in the reported CSV files).  This has been fixed as of ``4.1.3``.  Let me know if this doesn't fix it for you.
