### ISSUE TITLE
ies_use_prior_scaling

### ISSUE THREAD

**Issue by wkitlasten** [jtwhite79/pestpp#4]
This is more of a question than an issue with the software.

My ies parameter estimations are plagued by failed runs due to wonky parameter combinations resulting from a mostly uninformed parcov. In an attempt to reign in the updates and prevent so many failed reals I applied ++ies_use_prior_scaling("true"). Is that behavior unexpected by anyone but me? Does prior scaling typically reduce the magnitude parameter updates, or does it reduce some and increase others?

**Comment by jtwhite79** [comment]
In general, my experimenting with ``ies_use_prior_scaling(true)`` has shown that you need to pair it with a much larger ``ies_initial_lambda`` value to be successful.  It needs more experimentation, but, so far, that seems to be the trick...

**Comment by wkitlasten** [comment]
Is 3 orders of mag much larger?

**Comment by jtwhite79** [comment]
Yeah, that's about whats worked for me in the past...
